{"level":"error","message":"Logging in failed: User not found","stack":"Error: User not found\n    at Login$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/auth.js:47:13)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:145:13","timestamp":"2020-03-09 14:39:04"}
